{ name = "cli"
, dependencies =
  [ "aff"
  , "affjax"
  , "arrays"
  , "console"
  , "control"
  , "effect"
  , "either"
  , "foldable-traversable"
  , "httpurple"
  , "markup"
  , "maybe"
  , "node-buffer"
  , "node-fs"
  , "node-path"
  , "node-process"
  , "nullable"
  , "optparse"
  , "parsing"
  , "prelude"
  , "routing-duplex"
  , "strings"
  , "server"
  , "transformers"
  , "tuples"
  , "typelevel-prelude"
  ]
, packages = ../../packages.dhall
, sources = [ "src/**/*.purs" ]
}
